### ISSUE TITLE
The wiki is severely out of date, can I help on it?

### ISSUE THREAD

**Issue by Sovietsupporter69** [mcMMO-Dev/mcmmo-wiki-repo#4]
Hi mcmmo,
I'm a player who likes to use mcmmo but most of the things I want to use it for need significantly more detail than the wiki gives. While I don't mind doing my own testing to figure out these things myself, I feel its kinda wasted if the info I've found can't be shared with others (especially with the wiki in the state it is right now).

What I'm asking for is a branch I can edit to propose updates to the wiki, I don't mind if its never merged or if its ever merged you do a full re-wright of the pages I've made/altered, I just feel I have information I can use to fill in this currently lacking wiki.

**Comment by Chew** [comment]
You are free to [fork the repository](https://github.com/mcMMO-Dev/mcmmo-wiki-repo/fork) and make your edits there.

- You can learn more about forking [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo)
- You can learn more about Pull Requests [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests)

Make your changes to branches on your fork and make a pull request and we'll be happy to review and merge them in.

It's recommended to keep specific sets of changes to each branch/PR. For example, if you want to improve the archery page, keep all those changes to one branch so it's easier to track

**Comment by nossr50** [comment]
As chew pointed out, pull requests are how we are auditing wiki contributions, the prior wiki had a huge bot problem and was a never ending nightmare of making sure edits were from the "right" people.
